config/routes.rb
Rails.application.routes.draw do


   #顧客用
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }


  #管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get '/' => 'homes#top'
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show]
  end

  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about', as: 'about'
    get '/customers/my_page' => 'customers#show'
    get '/customers/information/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'
    get 'customers/detain' => "customers#detain"
    patch 'customers/out' => "customers#out"
    delete 'cart_items/destroy_all' => "cart_items#destroy_all"
    get 'orders/check' => "orders#check"
    post 'orders/check' => "orders#check"
    get 'orders/thanks' => "orders#thanks"
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    resources :items, only: [:index, :show, :new]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :orders, only: [:new, :create, :index, :show,]
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :addresses, dependent: :destroy
  has_many :cart_items
  has_many :orders

  def active_for_authentication?
    super && (is_deleted == false)
  end


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items
  has_many :order_items
  has_one_attached :image

  def get_image(size)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/nagano_cake/no_image.jpg')
      image.attach(io: File.open(file_path),filename: 'default-image.jpg',content_type: 'image/png')
    end
    image.variant(resize: size).processed
  end

  def with_tax_price
    (price * 1.1).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :customer
    has_many :order_items, dependent: :destroy


    enum payment_method: { credit_card: 0, transfer: 1 }


end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    customer = Customer.find(params[:id])
    customer.update(customer_params)
    redirect_to admin_customer_path(customer.id)
  end

  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email)
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    genre = Genre.new(genre_params)
    genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @orders = Order.page(params[:page]).per(10)
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def new
    @item = Item.new
  end

  def create
    item = Item.new(item_params)
    item.save
    redirect_to admin_item_path(item.id)
  end

  def index
    @items = Item.all
    @items = Item.page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item.id)
  end

  private
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items
    @total = @order.total_payment - @order.shopping_cost
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

   def after_sign_in_path_for(resource)
     admin_path
   end

   def after_sign_out_path_for(resource)
     new_admin_session_path
   end

   protected

   def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up,keys: [:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number])
   end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

   def after_sign_in_path_for(resource)
     customers_my_page_path
   end

   def after_sign_out_path_for(resource)
     about_path
   end

   protected

   def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up,keys: [:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number])
   end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div class ="container">
  <h2 class ="mt-3"><%= @customer.first_name %><%= @customer.last_name %>さんの会員情報編集</h2>

  <div class ="mt-4">
    <%= form_with model: @customer,url: admin_customer_path do |f|  %>
    <div>
      <div class = "form-group">
        <%= f.label :会員ID, '会員ID', class: "col-lg-2 col-form-label" %>
        <%= @customer.id %>
      </div>
      <div class ="form_group">
        <%= f.label :氏名, class: "col-lg-2 col-form-label" %>
        <%= f.text_field :first_name %>　<%= f.text_field :last_name %>
      </div>
      <div class ="form_group">
        <%= f.label :フリガナ, class: "col-lg-2 col-form-label" %>
        <%= f.text_field :first_name_kana %>　<%= f.text_field :last_name_kana %>
      </div>
      <div class ="form_group">
        <%= f.label :郵便番号, class: "col-lg-2 col-form-label" %>
        <%= f.text_field :postal_code %>
      </div>
      <div class ="form_group">
        <%= f.label :住所, class: "col-lg-2 col-form-label" %>
        <%= f.text_field :address, size: "50" %>
      </div>
      <div class ="form_group">
        <%= f.label :電話番号, class: "col-lg-2 col-form-label" %>
        <%= f.text_field :telephone_number %>
      </div>
      <div class ="form_group">
        <%= f.label :メールアドレス, class: "col-lg-2 col-form-label" %>
        <%= f.text_field :email %>
      </div>
      <div class ="form_group">
        <%= f.label :会員ステータス, class: "col-lg-2 col-form-label" %>
        <%= f.radio_button :is_deleted, 0, checked: "checked" %>
        <%= f.label :is_deleted, "有効" %>
        <%= f.radio_button :is_deleted, 1 %>
        <%= f.label :is_deleted, "無効" %>
      </div>

    </div>

      <%= f.submit "変更を保存", class: 'btn btn-success offset-lg-2 mt-2' %>


    </div>
    <% end %>
  </div>

</div>

app/views/admin/customers/index.html.erb
<div class ="container">
  <div>
    <h2 class ="mt-3">会員一覧</h2>
  </div>

  <div class ="col-lg-10 offset-lg-1">

    <table class ="table table-hover table-inverse">
       <therd>
        <tr class ='table-active'>
         <th>会員ID</th>
         <th>氏名</th>
         <th>メールアドレス</th>
         <th>ステータス</th>
        </tr>
       </therd>
       <tbody>
        <% @customers.each do |customer| %>
         <tr>
          <th><%= customer.id %></th>
          <th>
            <%= link_to admin_customer_path(customer) do %>
             <%= customer.first_name %><%= customer.last_name %>
            <% end %>
          </th>
          <th><%= customer.email %></th>
          <th>
           <% if customer.is_deleted %>
            <p class ="text-secondary">退会</p>
           <% else %>
            <p class ="text-success">有効</p>
           <% end %>
          </th>
         </tr>
        <% end %>
       </tbody>
      </table>


     <div class ="row justify-content-center">
      <%= paginate @customers %>
     </div>

    </div>
  </div>

app/views/admin/customers/show.html.erb
<div class ="container">
  <h2 class ="mt-3"><%= @customer.first_name %><%= @customer.last_name %>さんの会員詳細</h2>

  <table class ="table table-borderless mt-3">
     <tr>
       <th class ="col-lg-2">会員ID</th>
       <th><%= @customer.id %></th>
     </tr>
     <tr>
      <th class ="col-lg-2">氏名</th>
      <th><%= @customer.first_name %>  <%= @customer.last_name %></th>
     </tr>
     <tr>
      <th class ="col-lg-2">カナ</th>
      <th><%= @customer.first_name_kana %>  <%= @customer.last_name_kana %></th>
     </tr>
     <tr>
      <th class ="col-lg-2">郵便番号</th>
      <th><%= @customer.postal_code %></th>
     </tr>
     <tr>
      <th class ="col-lg-2">住所</th>
      <th><%= @customer.address %></th>
     </tr>
     <tr>
      <th class ="col-lg-2">電話番号</th>
      <th><%= @customer.telephone_number %></th>
     </tr>
     <tr>
      <th class ="col-lg-2">メールアドレス</th>
      <th><%= @customer.email %></th>
     </tr>
     <tr>
      <th class ="col-lg-2">会員ステータス</th>
      <th>
       <% if @customer.is_deleted %>
        <p class ="text-secondary">退会</p>
       <% else %>
        <p class ="text-success">有効</p>
       <% end %>
      </th>
     </tr>
     <tr>
       <th></th>
       <th><%= link_to "編集する", edit_admin_customer_path(@customer), class:"btn btn-success" %></th>
     </tr>
  </table>



</div>

app/views/admin/genres/edit.html.erb
<div class ="container">
  <div>
    <h2 class ="mt-3">ジャンル編集</h2>

    <div class ="mt-5">
      <%= form_with model: @genre, url: admin_genre_path(@genre.id),method: :patch do |f| %>
       <div class ="form-group form-inline">
         <%= f.label :name, "ジャンル名", class: "col-lg-2 col-form-label" %>
         <%= f.text_field :name, class: "col-lg-3" %>
         <%= f.submit '変更を保存', class: "btn btn-success offset-lg-1" %>
       </div>
      <% end %>
    </div>

  </div>
</div>

app/views/admin/genres/index.html.erb
<div class ="container">

    <h2 class ="mt-3">ジャンル一覧・追加</h2>

  <div class ="mt-3">
    <%= form_with model: @genre, url: admin_genres_path do |f| %>
    <div class ="form-group form-inline">
      <%= f.label :name, "ジャンル名", class: "col-lg-2 col-form-label" %>
      <%= f.text_field :name, class: "form-control col-lg-3" %>
      <%= f.submit '新規登録', class: "btn btn-success offset-lg-1" %>
    </div>
    <% end %>
  </div>

  <div class ="mt-5">
   <div class ="col-lg-5">
    <table class = "table table-inverse">
      <thead class ="thead-light">
        <tr>
          <th>　　ジャンル</th>
          <th colspan ="2"></th>
        </tr>
      </thead>
      <tbody>
        <% @genres.each do |genre| %>
        <tr>
          <td><%= genre.name %></td>
          <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn btn-success" %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
   </div>
  </div>
</div>

app/views/admin/items/edit.html.erb
<div class ="container">
  <h2 class ="mt-3">商品編集</h2>
   <div>

    <%= form_with model: @item, url: admin_item_path(@item.id), method: :patch do |f| %>
     <div class ="form-group">
      <%= f.label :image, "商品画像", class: "col-lg-2 col-form-label offset-lg-2" %>
      <%= f.file_field :image, accept: "image/*" %>
     </div>
     <div class ="form-group">
      <%= f.label :name, "商品名", class: "col-lg-2 col-form-label offset-lg-2" %>
      <%= f.text_field :name %>
     </div>
     <div class ="form-group">
      <%= f.label :introduction, "商品説明", class: "col-lg-2 col-form-label offset-lg-2" %>
      <%= f.text_area :introduction, rows: 6 %>
     </div>
     <div class ="form-group">
      <%= f.label :genre_id, "ジャンル", class: "col-lg-2 col-form-label offset-lg-2" %>
      <%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name) %>
     </div>
     <div class ="form-group">
      <%= f.label :price, "税抜価格", class: "col-lg-2 col-form-label offset-lg-2" %>
      <%= f.text_field :price %>円
     </div>
     <%= f.submit '変更を保存', class: "btn btn-success offset-lg-5" %>

    <% end %>

   </div>

</div>

app/views/admin/items/index.html.erb
<div class ="container">
  <div>
   <div class ="row">
    <h2 class ="col-lg-4 mt-3">商品一覧</h2>

    <div class ="offset-lg-6 mt-3">
     <%= link_to new_admin_item_path do %>
      <button type ="button" class ="btn btn-light rounded-circle">＋</button>
     <% end %>
    </div>
   </div>

   <div class ="mt-3">
    <table class ="table table-hover table-borderless">
     <therd>
      <tr class ='table-active'>
       <th>商品ID</th>
       <th>商品名</th>
       <th>税抜価格</th>
       <th>ジャンル</th>
      </tr>
     </therd>
     <tbody>
      <% @items.each do |item| %>
       <tr>
        <td><%= item.id %></td>
        <td><%= link_to item.name, admin_item_path(item) %></td>
        <td><%= item.price %></td>
        <td><%= item.genre.name %></td>
       </tr>
      <% end %>
     </tbody>
    </table>
   </div>

   <div class ="row justify-content-center">
    <%= paginate @items %>
   </div>

  </div>
</div>

app/views/admin/items/new.html.erb
<div class ="container">
  <div>

   <h2 class ="mt-3">商品新規登録</h2>

   <div>
    <%= form_with model: @item, url: admin_items_path do |f| %>
     <div class ="form-group">
      <%= f.label :image, "商品画像", class: "col-lg-2 col-form-label offset-lg-2" %>
      <%= f.file_field :image, accept: "image/*" %>
     </div>
     <div class ="form-group">
      <%= f.label :name, "商品名", class: "col-lg-2 col-form-label offset-lg-2" %>
      <%= f.text_field :name %>
     </div>
     <div class ="form-group">
      <%= f.label :introduction, "商品説明", class: "col-lg-2 col-form-label offset-lg-2" %>
      <%= f.text_area :introduction, rows: 6 %>
     </div>
     <div class ="form-group">
      <%= f.label :genre_id, "ジャンル", class: "col-lg-2 col-form-label offset-lg-2" %>
      <%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name) %>
     </div>
     <div class ="form-group">
      <%= f.label :price, "税抜価格", class: "col-lg-2 col-form-label offset-lg-2" %>
      <%= f.text_field :price %>円
     </div>
     <%= f.submit '新規登録',class: "btn btn-success offset-lg-5" %>
    <% end %>
   </div>

  </div>
</div>

app/views/admin/items/show.html.erb
<div class = "container">
 <h2 class ="mt-3">商品詳細</h2>
 <div class ="row" >

  <div class ="col-lg-5 mt-5">
   <% if @item.image.attached? %>
     <%= image_tag @item.image, size: "300x300" %>
   <% else %>
     <%= image_tag 'no_image', size: "300x300" %>
   <% end %>
  </div>


  <div class ="col-lg-7 mt-5">
    <table class ="table table-borderless">
      <tr>
       <th class ="col-lg-3">商品名</th>
       <th><%= @item.name %></th>
      </tr>
      <tr>
       <th class ="col-lg-3">商品説明</th>
       <th><%= @item.introduction %></th>
      </tr>
      <tr>
       <th class ="col-lg-3">ジャンル</th>
       <th><%= @item.genre.name %></th>
      </tr>
      <tr>
       <th class ="col-lg-3">税込価格<br>(税抜価格)</th>
       <th><%= @item.with_tax_price %>（<%= @item.price %>）円</th>
      </tr>
    </table>
    <div><%= link_to '編集する', edit_admin_item_path(@item), class: "btn btn-success offset-lg-2" %></div>
   </div>
 </div>
</div>

app/views/admin/orders/show.html.erb
<div class ="container">
  <div>
    <div>
      <h2 class ="mt-3">注文履歴詳細</h2>
      <table class = 'table table-borderless mt-3'>
        <tr>
          <th class ="col-lg-2"><strong>購入者</strong></th>
          <td><%= @order.customer.first_name %><%= @order.customer.last_name %></td>
        </tr>
        <tr>
          <th class ="col-lg-2">注文日</th>
          <td><%= @order.created_at.strftime('%Y/%m/%d %H:%M:%S') %></td>
        </tr>
        <tr>
          <th class ="col-lg-2">配送先</th>
          <td>
            <p>〒<%= @order.postal_code %>  <%= @order.address %></p>
            <p><%= @order.name %></p>
          </td>
        </tr>
        <tr>
          <th class ="col-lg-2">支払い方法</th>
          <td><%= @order.payment_method_i18n %></td>
        </tr>
        <tr>
          <th> </th>
          <td> </td>
        </tr>
      </table>
    </div>
  </div>

  <div>
    <div class ="row">
      <table class ='table table-borderd col-lg-8' >
        <thead class = 'thead-light'>
          <tr>
            <th>商品名</th>
            <th>単価(税込)</th>
            <th>数量</th>
            <th>小計</th>
            <th> </th>
          </tr>
        </thead>
        <tbody>
          <% @order_items.each do |order_item| %>
           <tr>
            <td><%= order_item.item.name %></td>
            <td><%= order_item.item.with_tax_price %></td>
            <td><%= order_item.amount %></td>
            <td><%= order_item.price %></td>
          </tr>
         <% end %>
        </tbody>
      </table>

      <table class ='table table-borderless col-lg-3 offset-lg-1'>
        <tr>
          <th><strong>商品合計</strong></th>
          <td><%= @total %>円</td>
        </tr>
        <tr>
          <th><strong>送料</strong></th>
          <td><%= @order.shopping_cost %>円</td>
        </tr>
        <tr>
          <th><strong>請求金額合計</strong></th>
          <td><%= @order.total_payment %>円</td>
        </tr>
      </table>
  </div>


</div>