config/routes.rb
Rails.application.routes.draw do


   #顧客用
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }


  #管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    get '/' => 'homes#top'
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show]
  end

  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about', as: 'about'
    get '/customers/my_page' => 'customers#show'
    get '/customers/information/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'
    get 'customers/detain' => "customers#detain"
    patch 'customers/out' => "customers#out"
    delete 'cart_items/destroy_all' => "cart_items#destroy_all"
    get 'orders/check' => "orders#check"
    post 'orders/check' => "orders#check"
    get 'orders/thanks' => "orders#thanks"
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    resources :items, only: [:index, :show, :new]
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :orders, only: [:new, :create, :index, :show,]
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :addresses, dependent: :destroy
  has_many :cart_items
  has_many :orders

  def active_for_authentication?
    super && (is_deleted == false)
  end


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items
  has_many :order_items
  has_one_attached :image

  def get_image(size)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/nagano_cake/no_image.jpg')
      image.attach(io: File.open(file_path),filename: 'default-image.jpg',content_type: 'image/png')
    end
    image.variant(resize: size).processed
  end

  def with_tax_price
    (price * 1.1).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :customer
    has_many :order_items, dependent: :destroy


    enum payment_method: { credit_card: 0, transfer: 1 }


end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    genre = Genre.new(genre_params)
    genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @orders = Order.page(params[:page]).per(10)
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def new
    @item = Item.new
  end

  def create
    item = Item.new(item_params)
    item.save
    redirect_to admin_item_path(item.id)
  end

  def index
    @items = Item.all
    @items = Item.page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item.id)
  end

  private
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items
    @total = @order.total_payment - @order.shopping_cost
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

   def after_sign_in_path_for(resource)
     customers_my_page_path
   end

   def after_sign_out_path_for(resource)
     about_path
   end

   protected

   def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up,keys: [:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number])
   end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>

  <body class ="d-flex flex-column vh-100">
    <header class ="border-bottom">
      <nav class ="navbar navbar-expand-lg navbar-light">
        <div class ="container">
          <div class ="navbar-brand"><%= image_tag 'nagano_cake/cakeshop_logo.png', size: "120x100" %></div>
          <button class ="navbar-toggler" type ="button" data-toggle ="collapse" data-target ="#navbarNavDropdown" aria-controls ="navbarNavDropdown" aria-expanded ="false" aria-label ="Toggle navigation">
            <span class ="navbar-toggler-icon"></span>
          </button>
          <div class ="collapse navbar-collapse" id ="navbarNavDropdown">
            <ul class ="navbar-nav ml-auto">
            <!--顧客がログインしているとき-->
            <% if customer_signed_in? %>
             <div>ようこそ、<%= current_customer.first_name %>さん！</div>
             <li class ="nav-item">
               <%= link_to 'マイページ', customers_my_page_path, class: 'nav-link text-dark' %>
             </li>

             <li class ="nav-item">
               <%= link_to '商品一覧', items_path, class: 'nav-link text-dark' %>
             </li>

             <li class ="nav-item">
               <%= link_to 'カート', cart_items_path, class: 'nav-link text-dark' %>
             </li>

             <li class ="nav-item">
               <%= link_to 'ログアウト', destroy_customer_session_path, method: :delete, class: 'nav-link text-dark' %>
             </li>

            <!--管理者がログインしているとき-->
            <% elsif  admin_signed_in? %>
             <li class ="nav-item">
               <%= link_to '商品一覧', admin_items_path, class: 'nav-link text-dark' %>
             </li>

             <li class ="nav-item">
               <%= link_to '会員一覧', admin_customers_path, class: 'nav-link text-dark' %>
             </li>

             <li class ="nav-item">
               <%= link_to '注文履歴一覧', admin_path, class: 'nav-link text-dark' %>
             </li>

             <li class ="nav-item">
               <%= link_to 'ジャンル一覧', admin_genres_path, class: 'nav-link text-dark' %>
             </li>

             <li class ="nav-item">
               <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' %>
             </li>

            <!--ログインしていないとき-->
            <% else %>
             <li class ="nav-item">
               <%= link_to 'About', about_path, class: 'nav-link text-dark' %>
             </li>

             <li class ="nav-item">
               <%= link_to '商品一覧', items_path, class: 'nav-link text-dark' %>
             </li>

             <li class ="nav-item">
               <%= link_to '新規登録', new_customer_registration_path, class: 'nav-link text-dark' %>
             </li>

             <li class ="nav-item">
               <%= link_to 'ログイン', new_customer_session_path, class: 'nav-link text-dark' %>
             </li>

            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main class ="mb-auto">
    <%= yield %>
    </main>

    <footer class = "border-top mb-5"></footer>
  </body>

</html>